window.DASHBOARD_DATA = [
  {
    "date": "2026-07-18",
    "season": "盛夏（高温高湿·祛湿温养季）",
    "dataSource": "联网搜索聚合（淘宝/天猫榜单、拼多多爆款、抖音营养品/护肤榜、1688源头工厂榜、饷店/细莫严选公开资料）。非平台官方API逐条爬取，价格/链接/发货时效以平台实时页面为准，上架前请人工复核。已按俏妃甄选要求避开自研品类（卫生巾、洗脸巾/棉柔巾、纸巾等）。",
    "weeklySuggestion": {
      "theme": "盛夏·祛湿温养双专区",
      "reason": "7月盛夏高温高湿，药食同源草本饮爆发（年轻人贡献超60%消费），三四线女性既追求祛湿消暑，又重视经期温养；红糖姜茶、祛湿茶、女性私护凝胶/益生菌为近期高复购、高认知品类，且客单价低、发货快，完美契合俏妃甄选人群，且不与自研日用棉品冲突。",
      "zones": [
        { "zone": "温养专区", "products": ["细莫红糖坚果姜茶", "阿胶枸杞红糖姜茶", "喜纯玉灵膏"] },
        { "zone": "祛湿轻饮专区", "products": ["红豆薏米祛湿茶", "蒲公英根茶", "茯苓荷叶饮"] },
        { "zone": "私护养护专区", "products": ["妇炎洁私处护理凝胶", "舒奈美女性益生菌", "南阳艾福美私密灸套盒"] },
        { "zone": "夏日护肤专区", "products": ["大宝SOD蜜", "薇诺娜润唇膏", "控油蓬松洗发水"] }
      ],
      "topPicks": [
        {
          "name": "细莫红糖坚果姜茶",
          "platform": "饷店/细莫严选",
          "price": "¥38.8起（礼盒装）",
          "brand": "细莫",
          "shipping": "48小时内",
          "reason": "女性专属温养，阿胶+枸杞+红枣+坚果，经期/月子场景刚需；天然无添加、价格亲民，与俏妃人群完全重合，夏季也热销，适合做温养专区引流款。"
        },
        {
          "name": "谷源堂蒲公英根茶 / 红豆薏米祛湿茶",
          "platform": "拼多多",
          "price": "百元内（拼多多热销榜）",
          "brand": "谷源堂等",
          "shipping": "48小时内",
          "reason": "夏季祛湿刚需、药食同源、百元内高性价比标杆，契合价格敏感人群；可组合成「祛湿轻饮专区」。"
        },
        {
          "name": "妇炎洁私处护理凝胶",
          "platform": "淘宝/天猫",
          "price": "¥129",
          "brand": "妇炎洁",
          "shipping": "48小时内（天猫超市）",
          "reason": "女性私护国民品牌，草本抑菌、知名度高、价格适中，与俏妃女性健康定位强相关，私护养护专区高转化单品，且非自研日用棉品。"
        },
        {
          "name": "舒奈美女性益生菌片",
          "platform": "1688（源头工厂）",
          "price": "工厂价（可贴牌）",
          "brand": "舒奈美生物",
          "shipping": "24小时内发货",
          "reason": "年销4.5万+件、复购率55%+、响应率0.95+，女性私护调理源头货，24h发货，可自有贴牌，供应链优选。"
        },
        {
          "name": "大宝SOD蜜补水保湿乳液",
          "platform": "淘宝/天猫",
          "price": "¥20.52",
          "brand": "大宝",
          "shipping": "48小时内",
          "reason": "2026年6月保湿榜TOP1、销量100万+，客单价极低、全民认知，三四线女性日常护肤刚需，夏日空调房基础保湿引流款。"
        }
      ]
    },
    "products": [
      {
        "platform": "淘宝/天猫",
        "name": "大宝SOD蜜补水保湿乳液面霜",
        "link": "https://s.taobao.com/search?q=大宝SOD蜜",
        "price": "¥20.52",
        "brand": "大宝",
        "shipping": "48小时内（天猫超市）",
        "hotReason": "2026年6月保湿护肤品女销量榜TOP1，销量100万+，折后价不足21元",
        "goodKeywords": ["保湿滋润", "性价比高", "温和不刺激", "大牌认知"],
        "badKeywords": ["香味偏浓", "偏滋润秋冬更合适"],
        "match": true,
        "matchReason": "客单价极低、全民认知度高，三四线价格敏感女性日常护肤刚需，引流首选"
      },
      {
        "platform": "淘宝/天猫",
        "name": "薇诺娜柔润修护润唇膏",
        "link": "https://s.taobao.com/search?q=薇诺娜润唇膏",
        "price": "¥39",
        "brand": "薇诺娜",
        "shipping": "48小时内",
        "hotReason": "2026年6月补水护理榜TOP9，销量10万+，敏感肌修护定位",
        "goodKeywords": ["修护唇部", "滋润", "敏感肌可用"],
        "badKeywords": ["偏小支"],
        "match": true,
        "matchReason": "敏感肌友好、国货认知高，夏季空调房唇部护理刚需，价格友好"
      },
      {
        "platform": "淘宝/天猫",
        "name": "可复美透明质酸钠修复贴",
        "link": "https://s.taobao.com/search?q=可复美修复贴",
        "price": "¥26.9",
        "brand": "可复美",
        "shipping": "48小时内（天猫超市）",
        "hotReason": "2026年6月补水护理榜TOP5，销量10万+，医美修护背书",
        "goodKeywords": ["敏感医美修护", "补水", "成分安全"],
        "badKeywords": ["单片价略高"],
        "match": true,
        "matchReason": "医美修护背书、低价尝鲜装，契合健康护肤人群"
      },
      {
        "platform": "淘宝/天猫",
        "name": "妇炎洁凝胶私处护理液（益生菌玻尿酸）",
        "link": "https://s.taobao.com/search?q=妇炎洁私处护理凝胶",
        "price": "¥129",
        "brand": "妇炎洁",
        "shipping": "48小时内（天猫超市）",
        "hotReason": "2026年6月补水护理榜TOP6，销量10万+，女性私护国民品牌",
        "goodKeywords": ["草本抑菌", "温和", "知名度高"],
        "badKeywords": ["部分觉得气味明显"],
        "match": true,
        "matchReason": "女性私护国民品牌，与俏妃人群高度重合，价格适中，非自研日用棉品"
      },
      {
        "platform": "淘宝/天猫",
        "name": "韩束聚时光精华水乳套装",
        "link": "https://s.taobao.com/search?q=韩束聚时光水乳",
        "price": "¥100",
        "brand": "韩束",
        "shipping": "48小时内",
        "hotReason": "2026年6月保湿榜TOP4，销量30万+，抗皱紧致定位",
        "goodKeywords": ["紧致淡纹", "性价比", "高销量"],
        "badKeywords": ["抗皱需长期"],
        "match": true,
        "matchReason": "高销量国货、百元价位契合价格敏感，可作为进阶护肤款"
      },
      {
        "platform": "拼多多",
        "name": "谷源堂蒲公英根茶",
        "link": "https://mobile.yangkeduo.com/search_result.html?search_key=蒲公英根茶",
        "price": "百元内",
        "brand": "谷源堂",
        "shipping": "48小时内（拼多多热销榜）",
        "hotReason": "常年稳居拼多多热销榜，百元内高性价比标杆，东北自有种植园原料",
        "goodKeywords": ["口感温润", "祛湿", "大容量家庭装"],
        "badKeywords": ["偏苦"],
        "match": true,
        "matchReason": "夏季祛湿刚需、价格敏感友好、拼多多爆款，契合健康养生人群"
      },
      {
        "platform": "拼多多",
        "name": "Swisse斯维诗铁+益生菌",
        "link": "https://mobile.yangkeduo.com/search_result.html?search_key=Swisse铁益生菌",
        "price": "¥63.5（百亿补贴）",
        "brand": "Swisse",
        "shipping": "48小时内（百亿补贴）",
        "hotReason": "拼多多百亿补贴爆料价，女性补铁补气血，孕妇可用",
        "goodKeywords": ["补气血", "知名进口牌", "补贴价"],
        "badKeywords": ["需坚持服用"],
        "match": true,
        "matchReason": "女性补气血、知名进口品牌补贴价，健康养生高转化"
      },
      {
        "platform": "拼多多",
        "name": "蔻芝琳控油蓬松洗发水",
        "link": "https://mobile.yangkeduo.com/search_result.html?search_key=控油蓬松洗发水",
        "price": "低价（拼多多）",
        "brand": "蔻芝琳",
        "shipping": "48小时内",
        "hotReason": "PDD宝藏好物推荐，油头救星，泡沫绵密、蓬松持久",
        "goodKeywords": ["控油蓬松", "油头救星", "性价比"],
        "badKeywords": ["干发需搭配护发素"],
        "match": true,
        "matchReason": "油头刚需、低价，契合县城女性日常洗护"
      },
      {
        "platform": "拼多多",
        "name": "叶黄素蒸汽眼罩",
        "link": "https://mobile.yangkeduo.com/search_result.html?search_key=叶黄素蒸汽眼罩",
        "price": "低价（拼多多）",
        "brand": "—",
        "shipping": "48小时内",
        "hotReason": "PDD好物推荐，草本清香、温热敷缓解眼疲劳",
        "goodKeywords": ["缓解眼疲劳", "温热敷", "即时体验好"],
        "badKeywords": ["单只价需算量"],
        "match": true,
        "matchReason": "久坐用眼人群广、即时体验好、低价易转化"
      },
      {
        "platform": "拼多多",
        "name": "健之佳生脉饮党参方",
        "link": "https://mobile.yangkeduo.com/search_result.html?search_key=生脉饮党参方",
        "price": "¥8.1（百亿补贴）",
        "brand": "健之佳",
        "shipping": "48小时内（百亿补贴）",
        "hotReason": "拼多多百亿补贴热销，夏季气虚自汗日常补气，每天不到1元",
        "goodKeywords": ["日常补气", "极致低价", "药食同源"],
        "badKeywords": ["中药味"],
        "match": true,
        "matchReason": "夏季气虚人群、极致低价，价格敏感人群引流利器"
      },
      {
        "platform": "抖音",
        "name": "喜纯玉灵膏",
        "link": "https://www.douyin.com/search/喜纯玉灵膏",
        "price": "¥100-300",
        "brand": "喜纯",
        "shipping": "48小时内",
        "hotReason": "抖音女性养生爆款，粉丝中女性占比74%-84%，场景化内容种草强",
        "goodKeywords": ["补气血", "场景化种草", "女性粉丝高"],
        "badKeywords": ["口感偏甜"],
        "match": true,
        "matchReason": "女性气血养生、内容种草强、价格区间友好"
      },
      {
        "platform": "抖音",
        "name": "诺特兰德营养品（维生素/益生菌/钙铁锌）",
        "link": "https://www.douyin.com/search/诺特兰德",
        "price": "低价（极致性价比）",
        "brand": "诺特兰德",
        "shipping": "48小时内",
        "hotReason": "抖音营养品榜单持续霸榜，超50万达人分销，极致性价比",
        "goodKeywords": ["性价比", "全家营养", "达人背书"],
        "badKeywords": ["需坚持"],
        "match": true,
        "matchReason": "极致性价比营养品，价格敏感友好，可作健康食品专区"
      },
      {
        "platform": "抖音",
        "name": "优斐斯5%氨甲环酸精华",
        "link": "https://www.douyin.com/search/优斐斯氨甲环酸精华",
        "price": "中高（院线护肤）",
        "brand": "优斐斯",
        "shipping": "48小时内",
        "hotReason": "抖音618面部精华爆款榜TOP5，用户好评9.4分，院线温和淡斑",
        "goodKeywords": ["温和淡斑", "院线背书", "好评9.4"],
        "badKeywords": ["需避光", "客单偏高"],
        "match": false,
        "matchReason": "功效护肤强但客单偏高，可作专区高价位补充，非价格敏感主线"
      },
      {
        "platform": "抖音",
        "name": "珀莱雅红宝石抗老紧致套装",
        "link": "https://www.douyin.com/search/珀莱雅红宝石套装",
        "price": "¥299-459",
        "brand": "珀莱雅",
        "shipping": "48小时内",
        "hotReason": "抖音Q1护肤TOP1，38大促GMV 5000-7500万",
        "goodKeywords": ["抗老紧致", "大牌平价线", "高销量"],
        "badKeywords": ["需长期使用", "客单超敏感线"],
        "match": false,
        "matchReason": "知名度高但客单超价格敏感线，作引流款而非主推"
      },
      {
        "platform": "1688（源头工厂）",
        "name": "舒奈美女性益生菌片",
        "link": "https://www.1688.com/?keywords=女性益生菌片",
        "price": "工厂价（可贴牌）",
        "brand": "舒奈美生物",
        "shipping": "24小时内发货",
        "hotReason": "年销量4.5万+件，月出货近4000件，复购率55%+，响应率0.95+",
        "goodKeywords": ["益生菌调理", "复购高", "可贴牌"],
        "badKeywords": ["需批发起订"],
        "match": true,
        "matchReason": "女性私护源头、24h发货、可贴牌，供应链优选"
      },
      {
        "platform": "1688（源头工厂）",
        "name": "红糖姜枣茶500g（女性温养）",
        "link": "https://www.1688.com/?keywords=红糖姜枣茶",
        "price": "工厂价（大容量）",
        "brand": "安徽济康/杭州通华等",
        "shipping": "最快12小时发货",
        "hotReason": "2026年6月女性养生姜茶销量10万+件，12小时极速发货",
        "goodKeywords": ["经期温养", "大容量", "发货极快"],
        "badKeywords": ["偏甜"],
        "match": true,
        "matchReason": "女性温养夏季也热、12h极速发货、低价，自有贴牌优选"
      },
      {
        "platform": "1688（源头工厂）",
        "name": "广州欧博气血调理凝胶",
        "link": "https://www.1688.com/?keywords=气血调理凝胶",
        "price": "单件成本低至0.52元",
        "brand": "广州欧博药业",
        "shipping": "24小时内",
        "hotReason": "2026年4月销量破10万件，用户复购率高达76%",
        "goodKeywords": ["气血循环", "吸收好", "复购极高"],
        "badKeywords": ["需坚持"],
        "match": true,
        "matchReason": "女性健康调理、高复购、工厂直供，自营贴牌优选"
      },
      {
        "platform": "1688（源头工厂）",
        "name": "南阳艾福美私密灸套盒",
        "link": "https://www.1688.com/?keywords=私密灸套盒",
        "price": "工厂价",
        "brand": "南阳艾福美",
        "shipping": "48小时内",
        "hotReason": "好评率99.6%，2.76万粉丝，私护领域品质标杆",
        "goodKeywords": ["艾灸温养", "好评极高", "女性健康"],
        "badKeywords": ["操作需学习"],
        "match": true,
        "matchReason": "女性温养、极高好评、可入温养专区"
      },
      {
        "platform": "饷店/细莫严选",
        "name": "细莫红糖坚果姜茶",
        "link": "https://s.taobao.com/search?q=细莫红糖坚果姜茶",
        "price": "¥38.8起（礼盒装）",
        "brand": "细莫",
        "shipping": "48小时内",
        "hotReason": "女性专属温养，阿胶+枸杞+红枣+核桃+坚果，经期/月子场景，天然无添加",
        "goodKeywords": ["暖身补气血", "天然无添加", "经期/月子"],
        "badKeywords": ["偏甜"],
        "match": true,
        "matchReason": "女性专属温养、与俏妃人群完全重合、价格亲民，温养专区核心"
      },
      {
        "platform": "饷店/细莫严选",
        "name": "细莫当归黑豆/红枣/山花蜜（食补组合）",
        "link": "https://s.taobao.com/search?q=细莫当归黑豆",
        "price": "亲民（组合装）",
        "brand": "细莫",
        "shipping": "48小时内",
        "hotReason": "女性食补养生组合，天然食材调理，常驻女神节套餐",
        "goodKeywords": ["天然食材", "调理", "组合丰富"],
        "badKeywords": ["需坚持"],
        "match": true,
        "matchReason": "女性食补养生组合、价格友好，可作食养专区"
      },
      {
        "platform": "饷店/细莫严选",
        "name": "星沙甄选玫瑰菩提/水漾面膜",
        "link": "https://s.taobao.com/search?q=星沙甄选面膜",
        "price": "礼盒装（轻奢）",
        "brand": "星沙甄选",
        "shipping": "48小时内",
        "hotReason": "女神节套餐核心单品，保湿滋润、玫瑰香氛，礼盒属性强",
        "goodKeywords": ["保湿", "玫瑰香", "礼盒属性"],
        "badKeywords": ["面膜需坚持"],
        "match": true,
        "matchReason": "女性护肤轻奢、礼盒属性，可作节日礼赠专区"
      },
      {
        "platform": "饷店/细莫严选",
        "name": "细莫玻色因灵芝抗皱系列（×华熙生物）",
        "link": "https://s.taobao.com/search?q=细莫玻色因抗皱",
        "price": "中高（科技抗衰）",
        "brand": "细莫×华熙生物",
        "shipping": "48小时内",
        "hotReason": "细莫携手华熙生物发布抗皱新品，玻色因+灵芝复合抗皱",
        "goodKeywords": ["科技抗皱", "全龄抗衰", "大厂背书"],
        "badKeywords": ["客单偏高"],
        "match": false,
        "matchReason": "科技抗衰但客单偏高，非价格敏感主线，作高端补充"
      }
    ]
  }
];
